source "http://rubygems.org"

ruby "2.3.3"

gem "mongo",             "~> 1.9.2"
gem "bson_ext",          "~> 1.9.2"
gem "cinch",             "~> 2.0.12"
gem "cinch-identify",    "~> 1.5.1"
gem "cinch-url-scraper", "~> 1.1.0"
gem "cinch-urbandict",   "~> 1.0.3"
gem "cinch-wikipedia",   "~> 1.0.3"
gem "cleverbot",         "~> 0.2.0"
gem "simple-rss",		 "~> 1.3.1"
gem "htmlentities", "~> 4.3", ">= 4.3.4"
gem "nokogiri", ">= 1.11.4"
gem "bson", ">= 3.0.4"
gem "mechanize", ">= 2.7.7"
